#! /bin/bash
. ./Validaciones

# Script de consulta del estado de maquinas

while getopts ":s:r:" opcion
do
    case $opcion in
        s ) salas="$OPTARG" ;;
        r ) rangos="$OPTARG" ;;
 	\?) echo "[-s a:e:f:et] [-r inicio:final/inicial1:final1/inicial2:final2/inicial3:final3] " ; exit ;;
    esac
done
shift $(($OPTIND -1))

declare -a sala
declare -a start
declare -a end

sala=(`obtener_salas "salas"`)
declare -p sala
start=(`obtener_rangos_iniciales "rangos"`)
declare -p start
end=(`obtener_rangos_finales "rangos"`)
declare -p end
validar_array_rangos "start" "end"
echo $?

# Validacion de rangos
old_long_start=${#start[@]}
if [ ${#s[@]} -gt ${#start[@]} ] ;  then
    for j in $(seq ${#start[@]} $((${#s[@]}-1))) ;  do
	start[$j]=1
	end[$j]=24
    done
fi
for i in $(seq 0 $(($old_long_start-1))) ; do
    validar_rangos "start[$i]" "end[$i]"
    tmp=$?
    start[$i]=${tmp[0]}
    end[$i]=${tmp[1]}
done

validar_salas "sala"
echo $?

declare -i fk=0

for sala in ${sala[*]} ; do    
    for i in $(seq ${start[$fk]} ${end[$fk]}) ; do
	boolean=$(eval echo \${$sala[$i]})
	if [ $boolean -eq 1 ] ; then
	    echo "$sala$i is (off)"
        else
            echo "$sala$i is (on)"
	fi
    done				     			
    fk=$fk+1
done
