#! /bin/bash
. ./Validaciones

# Script de consulta del estado de maquinas
encendidas=true
apagadas=true

while getopts ":s:r:ea" opcion
do
    case $opcion in
        s ) salas="$OPTARG" ;;
        r ) rangos="$OPTARG" ;;
	e ) apagadas=false ;;
	a ) encendidas=false ;;
 	\?) echo "[-s a:e:f:et] [-r inicio:final/inicial1:final1/inicial2:final2/inicial3:final3] [-a] [-e]" ; exit ;;
    esac
done
shift $(($OPTIND -1))

declare -a sala
declare -a start
declare -a end

sala=(`obtener_salas "salas"`)
start=(`obtener_rangos_iniciales "rangos"`)
end=(`obtener_rangos_finales "rangos"`)

# Validacion de rangos
old_long_start=${#start[@]}
if [ ${#sala[@]} -gt ${#start[@]} ] ;  then
    for j in $(seq ${#start[@]} $((${#sala[@]}-1))) ;  do
	start[$j]=1
	end[$j]=24
    done
fi

for i in $(seq 0 $(($old_long_start-1))) ; do
    if [ ${start[i]} -gt ${end[i]} ] ; then
	tmp=${start[$i]}
	start[$i]=${end[$i]}
	end[$i]=$tmp
    fi
done

validar_salas "sala"

validar_array_rangos "start" "end"

declare -i fk=0

dir=./DaemonLOG

 for sala in ${sala[*]} ; do    
     for i in $(seq ${start[$fk]} ${end[$fk]}) ; do
	 grep_out=$(grep "$sala$i " $dir | tail -1)
	 if $encendidas ; then
 	     echo $grep_out | grep on
	 fi
	 if $apagadas ; then
 	     echo $grep_out | grep off
	 fi
     done				     			
     fk=$fk+1
 done

# for sala in ${sala[*]} ; do    
#     for i in $(seq ${start[$fk]} ${end[$fk]}) ; do
# 	boolean=$(eval echo \${$sala[$i]})
# 	echo $boolean
# 	if [ $boolean -eq 1 ] ; then
# 	    echo "$sala$i is (off)"
#         else
#             echo "$sala$i is (on)"
# 	fi
#     done				     			
#     fk=$fk+1
# done